### ISSUE TITLE
Failed to activate the vue2-autocomplete package

### ISSUE THREAD

**Issue by AJMaxwell** [ealves-pt/atom-vue2-autocomplete#7]
[Enter steps to reproduce:]

1. Open Atom Beta

**Atom**: 1.32.0-beta0 x64
**Electron**: 2.0.9
**OS**: Ubuntu 16.04.5
**Thrown From**: [vue2-autocomplete](https://github.com/ealves-pt/atom-vue2-autocomplete) package 0.1.0-alpha.4

### Stack Trace

Failed to activate the vue2-autocomplete package

```
At Class constructor Disposable cannot be invoked without 'new'

TypeError: Class constructor Disposable cannot be invoked without 'new'
    at /packages/vue2-autocomplete/lib/provider.js:8:30)
    at VueAutocomplete.getProvider (/packages/vue2-autocomplete/lib/main.js:32:21)
    at Package.activateServices (/usr/share/atom-beta/resources/app/static/<embedded>:11:2901764)
    at Package.activateNow (/usr/share/atom-beta/resources/app/static/<embedded>:11:2898885)
    at measure (/usr/share/atom-beta/resources/app/static/<embedded>:11:2898209)
    at Package.measure (/usr/share/atom-beta/resources/app/static/<embedded>:11:2895840)
    at activationPromise.activationPromise.Promise (/usr/share/atom-beta/resources/app/static/<embedded>:11:2898069)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom-beta/resources/app/static/<embedded>:11:2898012)
    at PackageManager.activatePackage (/usr/share/atom-beta/resources/app/static/<embedded>:11:378441)
    at config.transactAsync (/usr/share/atom-beta/resources/app/static/<embedded>:11:378057)
    at Config.transactAsync (/usr/share/atom-beta/resources/app/static/<embedded>:11:328252)
    at PackageManager.activatePackages (/usr/share/atom-beta/resources/app/static/<embedded>:11:378007)
    at PackageManager.activate (/usr/share/atom-beta/resources/app/static/<embedded>:11:377625)
    at t.loadState.then (/usr/share/atom-beta/resources/app/static/<embedded>:1:641918)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.2 
atom-ctags 5.1.2 
atom-json-color 0.6.0 
magento2-tools 0.1.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
autocomplete-webpack 0.9.0 
busy-signal 1.4.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.25 
highlight-selected 0.14.0 
intentions 1.1.5 
iso8601-timestamp 0.1.1 
json-converter 0.2.4 
language-babel 2.85.0 
language-blade 0.41.2 
language-log 1.10.1 
language-nginx 0.8.0 
language-powershell 4.0.1 
language-vba 0.2.5 
language-vue 0.23.1 
laravel 0.7.1 
lint-sass-vue 1.0.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-markdownlint 1.0.2 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-stylelint 4.3.2 
linter-ui-default 1.7.1 
php-cs-fixer 4.1.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 1.1.0 
```

**Comment by AJMaxwell** [comment]
Same error for atom 1.32.0-beta0 x64
